# Generated by Django 3.2 on 2023-12-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_name', models.CharField(max_length=255)),
                ('team1_score', models.IntegerField()),
                ('team2_name', models.CharField(max_length=255)),
                ('team2_score', models.IntegerField()),
            ],
        ),
    ]
